const recommendations = [
	{
		active: true,
		brand: 'wojas',
		categories_ids: '["1","1","1008"]',
		category_1_url: 'https://wojas.pl/buty-damskie',
		category_2_url: 'https://wojas.pl/buty-damskie-botki',
		category_3_url: 'https://wojas.pl/buty-damskie-botki-wsuwane',
		category_level_1: 'Buty damskie',
		category_level_2: 'Botki',
		category_level_3: 'Wsuwane',
		category_path: 'Buty damskie|Botki|Wsuwane',
		color: 'czarny',
		cost_per_unit: null,
		cost_per_unit_local_currency: '',
		date_added: 1629985536,
		date_restock: '',
		description_long: '',
		discount_percentage: null,
		discount_value: null,
		engine_name: 'metric_1571815845',
		gender: 'Female',
		heel_height: '4,5 cm',
		image: 'https://cdn.wojas.eu/media/product/j/middle_img_90982.jpg',
		image_fullsize: 'https://cdn.wojas.eu/media/product/j/main_img_90982.jpg',
		insulation: 'nie',
		item_id: '39204',
		lead_time: null,
		local_currency: 'PLN',
		margin_percentage: '',
		margin_value: '',
		on_sale: 'False',
		original_price: 499,
		original_price_local_currency: 499,
		price: 499,
		price_local_currency: 499,
		product_id: '55117-51',
		rating: '',
		ratings_count: '',
		recommendation_id: '62cf24ef5d54a5c45755c8be',
		recommendation_source: 'model_non_personalized',
		recommendation_variant_id: null,
		returned_products: null,
		sale_description: '',
		sale_type: '',
		skin_type: 'licowa',
		stock_level: 813,
		style: 'urban',
		supplier: '',
		tags: '["Nowość","Bestseller"]',
		title: 'Czarne skórzane sztyblety damskie',
		type_of_fastening: 'wsuwane',
		type_of_footwear: 'jesienne',
		url: 'https://wojas.pl/czarne-skorzane-sztyblety-damskie-55117-51',
	},
	{
		active: true,
		brand: 'relaks',
		categories_ids: '["1","3","3"]',
		category_1_url: 'https://wojas.pl/buty-meskie',
		category_2_url: 'https://wojas.pl/buty-meskie-trzewiki',
		category_3_url: 'https://wojas.pl/buty-meskie-trzewiki-sneakers',
		category_level_1: 'Buty męskie',
		category_level_2: 'Trzewiki',
		category_level_3: 'Sneakers',
		category_path: 'Buty męskie|Trzewiki|Sneakers',
		color: 'jasny brąz',
		cost_per_unit: null,
		cost_per_unit_local_currency: '',
		date_added: 1637937527,
		date_restock: '',
		description_long: '',
		discount_percentage: 20,
		discount_value: 79.8,
		engine_name: 'metric_1571815845',
		gender: 'Male',
		heel_height: '3 cm',
		image: 'https://cdn.wojas.eu/media/product/j/middle_img_97729.jpg',
		image_fullsize: 'https://cdn.wojas.eu/media/product/j/main_img_97729.jpg',
		insulation: 'nie',
		item_id: '39501',
		lead_time: null,
		local_currency: 'PLN',
		margin_percentage: '',
		margin_value: '',
		on_sale: 'True',
		original_price: 399,
		original_price_local_currency: 399,
		price: 319.2,
		price_local_currency: 319.2,
		product_id: '24003-73',
		rating: '',
		ratings_count: '',
		recommendation_id: '62cf24ef5d54a5c45755c8be',
		recommendation_source: 'model_non_personalized',
		recommendation_variant_id: null,
		returned_products: null,
		sale_description: 'Wyprzedaż',
		sale_type: '["Wyprzedaż"]',
		skin_type: 'nubuk + sk. tłocz.',
		stock_level: 140,
		style: 'casual',
		supplier: '',
		tags: '["Wyprzedaż"]',
		title: 'Czarne trzewiki RELAKS z jasnobrązową wstawką',
		type_of_fastening: 'sznurowane',
		type_of_footwear: 'jesienne',
		url: 'https://wojas.pl/czarne-trzewiki-RELAKS-z-jasnobrazowa-wstawka-24003-73',
	},
	{
		active: true,
		brand: 'relaks',
		categories_ids: '["1","40","1009"]',
		category_1_url: 'https://wojas.pl/buty-damskie',
		category_2_url: 'https://wojas.pl/buty-damskie-sniegowce',
		category_3_url: 'https://wojas.pl/buty-damskie-sniegowce-pozostale',
		category_level_1: 'Buty damskie',
		category_level_2: 'Śniegowce',
		category_level_3: 'Pozostałe',
		category_path: 'Buty damskie|Śniegowce|Pozostałe',
		color: 'czarny',
		cost_per_unit: null,
		cost_per_unit_local_currency: '',
		date_added: 1665055549,
		date_restock: '',
		description_long: '',
		discount_percentage: null,
		discount_value: null,
		engine_name: 'metric_1571815845',
		gender: 'Female',
		heel_height: '6,5 cm',
		image: 'https://cdn.wojas.eu/media/product/j/middle_img_122468.jpg',
		image_fullsize: 'https://cdn.wojas.eu/media/product/j/main_img_122468.jpg',
		insulation: 'tak',
		item_id: '40911',
		lead_time: null,
		local_currency: 'PLN',
		margin_percentage: '',
		margin_value: '',
		on_sale: 'False',
		original_price: 499,
		original_price_local_currency: 499,
		price: 499,
		price_local_currency: 499,
		product_id: 'R35000-11',
		rating: '',
		ratings_count: '',
		recommendation_id: '62cf24ef5d54a5c45755c8be',
		recommendation_source: 'model_non_personalized',
		recommendation_variant_id: null,
		returned_products: null,
		sale_description: '',
		sale_type: '',
		skin_type: 'tworzywo sztuczne+ortalion',
		stock_level: 497,
		style: 'casual',
		supplier: '',
		tags: '["Nowość"]',
		title: 'RELAKS czarne śniegowce damskie z połączenia skóry i ortalionu',
		type_of_fastening: 'wsuwane',
		type_of_footwear: 'zimowe',
		url: 'https://wojas.pl/RELAKS-czarne-sniegowce-damskie-z-polaczenia-skory-i-ortalionu-R35000-11',
	},
	{
		active: true,
		brand: 'wojas',
		categories_ids: '["4","17"]',
		category_1_url: 'https://wojas.pl/akcesoria-meskie',
		category_2_url: 'https://wojas.pl/akcesoria-meskie-rekawiczki',
		category_3_url: '',
		category_level_1: 'Akcesoria męskie',
		category_level_2: 'Rękawiczki',
		category_level_3: '',
		category_path: 'Akcesoria męskie|Rękawiczki',
		color: 'czarny',
		cost_per_unit: null,
		cost_per_unit_local_currency: '',
		date_added: 1609253251,
		date_restock: '',
		description: 'Męskie rękawiczki ze skóry licowej',
		description_long: '',
		discount_percentage: null,
		discount_value: null,
		engine_name: 'metric_1571815845',
		gender: 'Male',
		heel_height: '',
		image: 'https://cdn.wojas.eu/media/product/j/middle_img_73573.jpg',
		image_fullsize: 'https://cdn.wojas.eu/media/product/j/main_img_73573.jpg',
		insulation: '',
		item_id: '38178',
		lead_time: null,
		local_currency: 'PLN',
		margin_percentage: '',
		margin_value: '',
		on_sale: 'False',
		original_price: 129,
		original_price_local_currency: 129,
		price: 129,
		price_local_currency: 129,
		product_id: '98117-51',
		rating: '',
		ratings_count: '',
		recommendation_id: '62cf24ef5d54a5c45755c8be',
		recommendation_source: 'model_non_personalized',
		recommendation_variant_id: null,
		returned_products: null,
		sale_description: '',
		sale_type: '',
		skin_type: 'licowa',
		stock_level: 187,
		style: '',
		supplier: '',
		tags: '',
		title: 'Skórzane rękawiczki męskie w kolorze czarnym',
		type_of_fastening: '',
		type_of_footwear: 'zimowe',
		url: 'https://wojas.pl/skorzane-rekawiczki-meskie-w-kolorze-czarnym-98117-51',
	},
];

const recommendationBox = document.querySelector('.box-recomendation__wrapper');

window.onload = function () {
	// Pobierz dane z zapytania i wstaw je do elementu o klasie ".box-recomendation"
	// Iteruj po pobranych danych i wstaw je do elementu ".box-recomendation"
	recommendations.forEach((item) => {
		recommendationBox.innerHTML += `
                <div class="box-recomendation__item">
                        <a href=${item.url} </a>
                        <div class="box-recomendation__image">
                            <div class="box-recomendation__tag" ></div>
                            <img class="lazy" src="${item.image}" alt="${item.title}" />
                        </div>
                        <div class="box-recomendation__price">
                            <div class="box-recomendation__price-regular" >
                                <span> ${item.price} zł</span>
                            </div>
                        </div>
                        <div class="box-recomendation__model">
                            <span> ${item.product_id} </span>
                        </div>
                        <div class="box-recomendation__name">
                            <span> ${item.title} </span>
                        </div>
                </div>`;
	});
};
